# Docker build tag and push
name: Release
on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    if: "! contains( github.event.head_commit.message, 'Bump version')"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.gcv.outputs.NEW_TAG }}
    steps:
      - name: Context
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Bump version and tag
        uses: jaumann/github-bumpversion-action@v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          DAFAULT_BUMP: major
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GH_PAT }}
      #     branch: ${{ github.ref }}
      - name: Get current version
        id: gcv
        run: |
          git tag -l
          echo NEW_TAG=$(grep "current_version =" .bumpversion.cfg | cut -d " " -f3) >> "$GITHUB_OUTPUT"

  docker-push:
    if: "! contains( github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - env:
          NEW_TAG: ${{ needs.bump-version.outputs.new_tag }}
        run: |
          echo $NEW_TAG
      # - name: Context
      #   uses: actions/checkout@v4
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Docker login
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_PAT }}
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ needs.bump-version.outputs }}
        