# Run tests
name: Run tests
on:
  pull_request:
    branches:
      - 'main'

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Chromium
        uses: browser-actions/setup-chrome@v1
      - name: Setup Python            
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - name: Install pipenv
        run: pip install pipenv==2023.12.1
      - name: Install py dependencies
        run: pipenv
             install -d
      - name: Run tests
        run: pipenv
             run pytest --verbosity 2
