# Run tests
name: run tests
on: [push]

jobs:
    dependencies:
        runs-on: ubuntu-latest
        env:
          PIPENV_VENV_IN_PROJECT: '1'
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Install Chromium
              uses: browser-actions/setup-chrome@v1
            - name: Setup Python
              uses: actions/setup-python@v5.1.0
              with:
                python-version: '3.10.12'
                cache: 'pipenv'
            - name: Install pipenv
              run: pip install pipenv==2023.12.1
            - run:
                pwd && ls -la
                pipenv update
                pipenv install --dev
                pipenv run pytest
                
                
